# Generated by Django 4.2.6 on 2023-10-28 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_inicial_e_cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
