# Generated by Django 4.2.6 on 2023-10-31 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_inicial_e_cadastro', '0003_usuario_senha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ator',
            fields=[
                ('ator_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_ator', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('nacionalidade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaFilme',
            fields=[
                ('categoria_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Diretor',
            fields=[
                ('diretor_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_diretor', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('nacionalidade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('filme_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('sinopse', models.TextField()),
                ('ano_lancamento', models.PositiveIntegerField()),
                ('classificacao_indicativa', models.CharField(max_length=10)),
                ('idioma', models.CharField(max_length=50)),
                ('pontuacao_media', models.DecimalField(decimal_places=2, max_digits=3)),
                ('url_imagem_capa', models.URLField(max_length=255)),
                ('url_trailer', models.URLField(max_length=255)),
                ('diretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inicial_e_cadastro.diretor')),
            ],
        ),
        migrations.CreateModel(
            name='FilmeCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inicial_e_cadastro.categoriafilme')),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inicial_e_cadastro.filme')),
            ],
        ),
        migrations.CreateModel(
            name='Elenco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inicial_e_cadastro.ator')),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inicial_e_cadastro.filme')),
            ],
        ),
        migrations.CreateModel(
            name='DiretorFilme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inicial_e_cadastro.diretor')),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inicial_e_cadastro.filme')),
            ],
        ),
    ]
