# Generated by Django 4.2.6 on 2023-11-15 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_inicial_e_cadastro', '0004_ator_categoriafilme_diretor_filme_filmecategoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id_avaliacao', models.AutoField(primary_key=True, serialize=False)),
                ('classificacao', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1)),
                ('comentario', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_cat', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_cat', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidade',
            fields=[
                ('id_nacionalidade', models.IntegerField(primary_key=True, serialize=False)),
                ('nacionalidade', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='diretorfilme',
            name='diretor',
        ),
        migrations.RemoveField(
            model_name='diretorfilme',
            name='filme',
        ),
        migrations.RemoveField(
            model_name='elenco',
            name='ator',
        ),
        migrations.RemoveField(
            model_name='elenco',
            name='filme',
        ),
        migrations.RemoveField(
            model_name='filmecategoria',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='filmecategoria',
            name='filme',
        ),
        migrations.RenameField(
            model_name='ator',
            old_name='ator_id',
            new_name='id_ator',
        ),
        migrations.RenameField(
            model_name='diretor',
            old_name='diretor_id',
            new_name='id_diretor',
        ),
        migrations.RenameField(
            model_name='filme',
            old_name='filme_id',
            new_name='id_filme',
        ),
        migrations.RemoveField(
            model_name='ator',
            name='nome_ator',
        ),
        migrations.RemoveField(
            model_name='diretor',
            name='nome_diretor',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='classificacao_indicativa',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='pontuacao_media',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='url_imagem_capa',
        ),
        migrations.AddField(
            model_name='ator',
            name='nome',
            field=models.CharField(default='Nome Padrão', max_length=50),
        ),
        migrations.AddField(
            model_name='diretor',
            name='nome',
            field=models.CharField(default='Nome Padrão', max_length=50),
        ),
        migrations.AddField(
            model_name='filme',
            name='class_indicativa',
            field=models.CharField(default='Livre', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filme',
            name='url_capa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='filme',
            name='ano_lancamento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='filme',
            name='idioma',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='filme',
            name='sinopse',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='filme',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='filme',
            name='url_trailer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=60),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='CategoriaFilme',
        ),
        migrations.DeleteModel(
            name='DiretorFilme',
        ),
        migrations.DeleteModel(
            name='Elenco',
        ),
        migrations.DeleteModel(
            name='FilmeCategoria',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='filme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inicial_e_cadastro.filme'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inicial_e_cadastro.usuario'),
        ),
        migrations.AddField(
            model_name='filme',
            name='categoria',
            field=models.ForeignKey(default='Sem categoria', on_delete=django.db.models.deletion.CASCADE, to='app_inicial_e_cadastro.categoria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ator',
            name='nacionalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inicial_e_cadastro.nacionalidade'),
        ),
        migrations.AlterField(
            model_name='diretor',
            name='nacionalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inicial_e_cadastro.nacionalidade'),
        ),
    ]
