# Generated by Django 4.2.6 on 2023-11-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inicial_e_cadastro', '0005_avaliacao_categoria_nacionalidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='id_cat',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
