# Generated by Django 4.2.6 on 2023-11-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inicial_e_cadastro', '0007_alter_categoria_id_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ator',
            name='id_ator',
        ),
        migrations.AddField(
            model_name='ator',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ator',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='comentario',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='id_cat',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='diretor',
            name='id_diretor',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='diretor',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='filme',
            name='id_filme',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='filme',
            name='idioma',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='filme',
            name='sinopse',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='filme',
            name='url_capa',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='filme',
            name='url_trailer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='nacionalidade',
            name='id_nacionalidade',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nacionalidade',
            name='nacionalidade',
            field=models.CharField(default='Desconhecido', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
