# Generated by Django 4.2.6 on 2023-11-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inicial_e_cadastro', '0008_remove_ator_id_ator_ator_id_alter_ator_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='id_cat',
        ),
        migrations.AddField(
            model_name='categoria',
            name='id',
            field=models.BigAutoField(auto_created=True, default='nada', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
