# Generated by Django 4.2.6 on 2023-11-17 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inicial_e_cadastro', '0010_remove_categoria_id_categoria_id_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nacionalidade',
            name='id_nacionalidade',
            field=models.CharField(max_length=2, primary_key=True, serialize=False),
        ),
    ]
